name: Daily Snowflake to HubSpot Sync

on:
  schedule:
    # - cron: "0 0 * * *"
    - cron: "0 0 31 2 *"

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: transpile and run sync script
        run: npm run start
