name: Create custom account object

on: workflow_dispatch

jobs:
  sync-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: transpile and run initialise script that creates the custom object type
        run: npm run init
